server:
  port: 8200
spring:
  application:
    name: springcloud-payment-service-consul
  cloud:
    consul:
      host: localhost   #这里仅做测试，所以安装了windows版本consul，并运行consul agent -dev启动
      port: 8500
      discovery:
        service-name: ${spring.application.name}