server:
  port: 8300
spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 192.168.199.128:7890
management:
  endpoints:
    web:
      exposure:
        include: '*'