server:
  port: 3001
spring:
  application:
    name: springcloud-config-server3001
  cloud:
    config:
      server:
        #可通过（label为分支）:
        # /{label}/{application}-{profile}.yml
        # /{application}-{profile}.yml
        # /{label}/{application}-{profile}.properties
        # /{application}-{profile}.properties
        # /{application}/{profile}[/{label}]      返回的是json串
        git:
          uri: https://github.com/iefihz/springcloud-config-server3001.git
#          search-paths:
#            - springcloud-config-server3001
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: config-server3001