server:
  port: 80
spring:
  application:
    name: consumer-order80-eureka-hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: order80-eureka-hystrix

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.iefihz.springcloud.feign.PaymentFeignClient: debug