server:
  port: 2002
spring:
  application:
    name: springcloud-seata-storage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seata-storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.iefihz.seata.entity

eureka:
  client:
    register-with-eureka: true  #是否注册到eureka服务端
    fetch-registry: true  #配合ribbon集群的时候需要设置为true，单节点不影响使用
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true   #访问路径可以显示ip
    instance-id: seata-storage-2002  #配置显示的是这个微服务实例id，而不是显示自己的主机名

#    需要关闭自我保护模式
#    lease-renewal-interval-in-seconds: 1    #每隔1s发送一个心跳包，默认30s
#    lease-expiration-duration-in-seconds: 2   #eureka service 距离上一次收到这个实例的心跳包隔2s则把这个实例移除，默认90s