server:
  port: 9500
spring:
  application:
    name: hystrix-turbine9500
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: turbine9500

turbine:
  aggregator:
    clusterConfig: PROVIDER-PAYMENT-SERVICE-HYSTRIX
  appConfig: provider-payment-service-hystrix
#  instanceUrlSuffix:
#    PROVIDER-PAYMENT-SERVICE-HYSTRIX: hystrix.stream

#配置多个（也可以像上面配置多个用逗号分隔）：
#turbine:
#  aggregator:
#    clusterConfig: default
#  appConfig: xxx,yyy
#  clusterNameExpression: "'default'" 或者 new String("default")