CREATE TABLE t_payment (
`id` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'id',
`serial` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '支付流水号'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;